### ISSUE TITLE
vertus help not run

### ISSUE THREAD

**Issue by kingvavasav** [Axcent-ape/VertusBot#7]
C:\Users\ani\Desktop\sc\VertusBot-main>main.py
Traceback (most recent call last):
  File "C:\Users\ani\Desktop\sc\VertusBot-main\main.py", line 1, in <module>
    from utils.core.telegram import Accounts
  File "C:\Users\ani\Desktop\sc\VertusBot-main\utils\core\__init__.py", line 1, in <module>
    from .logger import logger
  File "C:\Users\ani\Desktop\sc\VertusBot-main\utils\core\logger.py", line 3, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by pharaoh347** [comment]
pip3 install -r requirements.txt
